# This GitHub Actions workflow runs the data ingestor script on a schedule

name: Daily F1 Data Ingestion

on:
  # Run this workflow every day at 03:00 UTC
  schedule:
    - cron: '0 3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ingest-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Run data ingestion script
        # The MONGO_URI is securely stored as a GitHub secret
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python backend/data_ingestor.py

